#!/bin/bash

cd python

if [[ $1 == "run" || $1 == "test" ]]
then
    python3 main.py ${1} ${2} ${3}
fi

if [ $1 == "init" ]
then
    mkdir ../aoc${2}/day_${3}
    cp ./day_X/* ../aoc${2}/day_${3}/
fi 