#!/bin/bash

cd python

if [[ $1 == "run" || $1 == "test" ]]
then
    PYTHONPATH=$(pwd)/.. python3 main.py ${1} ${2} ${3} ${4}
fi

if [ $1 == "init" ]
then
    mkdir ./aoc${2}/day_${3}
    cp ./python/day_X/* ./aoc${2}/day_${3}/
fi 